# Site settings
title: Lucas Barros
email: lucsbarros@gmail.com
description: "some stuffs about frontend development and design, a little about me, what I think and know..."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucasbarros.github.io" # the base hostname & protocol for your site
twitter_username: _lucasbarros
github_username:  lucasbarros

# Build settings
markdown: kramdown
